### ISSUE TITLE
显存随着训练步数不断上升

### ISSUE THREAD

**Issue by Chenfei-Kang** [PaddlePaddle/PaddleNLP#1179]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP=2.1.0 PaddlePaddle=2.1.1-gpu
2）系统环境：Windows ，python =3.7  和 AI studio jupyter 高级版(两个都试了)
- 复现信息：如为报错，请给出复现环境、复现步骤

**报错信息**
Out of memory error on GPU 0. Cannot allocate 16.781494MB memory on GPU 0, 7.993042GB memory has been allocated and available memory is only 7.125000MB.
详细描述：
刚开始跑的时候，模型加数据大约在 5.7GB 显存左右，然后跑着跑着就到7GB了，然后大约3600步显存就炸了。**用AI studio的v100 16GB 显卡跑也一样**，运行着运行着显存就炸了，不知道问题出在哪里。
代码来源于2021CCF 千言-问题匹配鲁棒性评测大赛的百度官方baseline，但是跑着跑着显存就上去了，paddle又没有提供手动释放显存的API，我也不知道显存到底泄露在哪里。总之就是代码跑着跑着显存不断上升，跑到大约3600步就会报错。
**尝试的解决方法**
export FLAGS_eager_delete_tensor_gb=0 **(没用，还是会炸)**
export FLAGS_fast_eager_deletion_mode=1 **也没用**
在验证时已经加了

所以为什么会炸，照常理说一个batch跑完了内存就释放了，显存会始终维持在5.7GB左右，验证的时候也加了no_grad().

**代码步骤**
```python

# 下面的代码就是预训练+Fine-Tune

@paddle.no_grad()
def evaluate(model, criterion, metric, data_loader):
    """
    Given a dataset, it evals model and computes the metric.
    Args:
        model(obj:`paddle.nn.Layer`): A model to classify texts.
        data_loader(obj:`paddle.io.DataLoader`): The dataset loader which generates batches.
        criterion(obj:`paddle.nn.Layer`): It can compute the loss.
        metric(obj:`paddle.metric.Metric`): The evaluation metric.
    """
    model.eval()
    metric.reset()
    losses = []
    total_num = 0

    for batch in tqdm.tqdm(data_loader):
        input_ids, token_type_ids, labels = batch
        total_num += len(labels)
        logits, _ = model(input_ids=input_ids, token_type_ids=token_type_ids, do_evaluate=True)
        loss = criterion(logits, labels)
        losses.append(loss.numpy())
        correct = metric.compute(logits, labels)
        metric.update(correct)
        accu = metric.accumulate()

    print("dev_loss: {:.5}, accuracy: {:.5}, total_num:{}".format(np.mean(losses), accu, total_num))
    model.train()
    metric.reset()
    return accu


def do_train():
    paddle.set_device(args.device)
    rank = paddle.distributed.get_rank()
    if paddle.distributed.get_world_size() > 1:
        paddle.distributed.init_parallel_env()

    set_seed(args.seed)

    train_ds = load_dataset(
        read_text_pair, data_path=args.train_set, is_test=False, lazy=False) # 505939

    dev_ds = load_dataset(
        read_text_pair, data_path=args.dev_set, is_test=False, lazy=False) # 28802

    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
        'ernie-gram-zh')
    tokenizer = ppnlp.transformers.ErnieGramTokenizer.from_pretrained(
        'ernie-gram-zh')

    trans_func = partial(
        convert_example,
        tokenizer = tokenizer,
        max_seq_length=args.max_seq_length)

    batchify_fn = lambda samples, fn=Tuple(
        Pad(axis=0, pad_val=tokenizer.pad_token_id),  # text_pair_input
        Pad(axis=0, pad_val=tokenizer.pad_token_type_id),  # text_pair_segment
        Stack(dtype="int64")  # label
    ): [data for data in fn(samples)]

    train_data_loader = create_dataloader(
        train_ds,
        mode='train',
        batch_size=args.train_batch_size,
        batchify_fn=batchify_fn,
        trans_fn=trans_func)

    dev_data_loader = create_dataloader(
        dev_ds,
        mode='dev',
        batch_size=args.eval_batch_size,
        batchify_fn=batchify_fn,
        trans_fn=trans_func)

    model = QuestionMatching(pretrained_model, rdrop_coef=args.rdrop_coef)

    if args.init_from_ckpt and os.path.isfile(args.init_from_ckpt):
        state_dict = paddle.load(args.init_from_ckpt)
        model.set_dict(state_dict)



    model = paddle.DataParallel(model)

    num_training_steps = len(train_data_loader) * args.epochs

    lr_scheduler = LinearDecayWithWarmup(args.learning_rate, num_training_steps,
                                         args.warmup_proportion)

    # Generate parameter names needed to perform weight decay.
    # All bias and LayerNorm parameters are excluded.
    decay_params = [
        p.name for n, p in model.named_parameters()
        if not any(nd in n for nd in ["bias", "norm"])
    ]
    optimizer = paddle.optimizer.AdamW(
        learning_rate=lr_scheduler,
        parameters = model.parameters(),
        weight_decay=args.weight_decay,
        apply_decay_param_fun=lambda x: x in decay_params)

    criterion = paddle.nn.loss.CrossEntropyLoss()

    metric = paddle.metric.Accuracy()

    global_step = 0
    best_accuracy = 0.0

    tic_train = time.time()
    log_file = open("log.txt", mode = 'w')
    for epoch in range(1, args.epochs + 1):
        for step, batch in enumerate(train_data_loader, start=1):
            input_ids, token_type_ids, labels = batch
            logits1, kl_loss = model(input_ids=input_ids, token_type_ids=token_type_ids)
            correct = metric.compute(logits1, labels)
            metric.update(correct)
            acc = metric.accumulate()

            ce_loss = criterion(logits1, labels)
            if kl_loss > 0:
                loss = ce_loss + kl_loss * args.rdrop_coef
            else:
                loss = ce_loss
            global_step += 1
            if global_step % 10 == 0 and rank == 0:
                print(
                    "global step %d, epoch: %d, batch: %d, loss: %.4f, ce_loss: %.4f., kl_loss: %.4f, accu: %.4f, speed: %.2f step/s"
                    % (global_step, epoch, step, loss, ce_loss, kl_loss, acc,
                       10 / (time.time() - tic_train)))
                log_file.write("global step %d, epoch: %d, batch: %d, loss: %.4f, ce_loss: %.4f., kl_loss: %.4f, accu: %.4f, speed: %.2f step/s \n"
                    % (global_step, epoch, step, loss, ce_loss, kl_loss, acc,
                       10 / (time.time() - tic_train)))
                tic_train = time.time()

            loss.backward()
            optimizer.step()
            lr_scheduler.step()
            optimizer.clear_grad()

            if global_step % args.eval_step == 0 and rank == 0:
                accuracy = evaluate(model, criterion, metric, dev_data_loader)
                if accuracy > best_accuracy:
                    save_dir = os.path.join(args.save_dir, "model_%d" % global_step)
                    if not os.path.exists(save_dir):
                        os.makedirs(save_dir)
                    save_param_path = os.path.join(save_dir, 'model_state.pdparams')
                    paddle.save(model.state_dict(), save_param_path)
                    tokenizer.save_pretrained(save_dir)
                    best_accuracy = accuracy

            if global_step == args.max_steps:
                return
    log_file.close()

if __name__ == "__main__":

    do_train()
```

**Comment by Chenfei-Kang** [comment]
已解决，不过建议增加一个手动回收显存的API，thanks

**Comment by EnHuiPug** [comment]
请问如何解决的。。。谢谢🙏

**Comment by Chenfei-Kang** [comment]
> 请问如何解决的。。。谢谢🙏


这个bug应该是在循环或者条件语句下创建的临时变量显存不会自动回收，需要自己手动删除，用下面两个语句。
1. 先`import gc`，在训练的过程中创建了变量a，然后在一轮循环时 `del a`， 然后在之后立马`gc.collect()`
2. 建议升级到paddle2.2.0，用语句paddle.device.cuda.empty_cache()语句回收。

代码示例：
```python
a = paddle.tensor(.........)
# 使用完毕
del a
gc.collect()
paddle.device.cuda.empty_cache()
```

**Comment by xiabingbao-ok** [comment]
请问是如何解决的？？？paddle.device.cuda.empty_cache()语句回收 代码加载你上述代码的哪一个步骤呀
