### ISSUE TITLE
Cuda error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by ZHANG-GuiGui** [PaddlePaddle/PaddleNLP#1193]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）paddlenlp 2.0.8 paddlepaddle-gpu 2.1.3
2）系统环境：Linux python 3.6.3

将 https://github.com/PaddlePaddle/PaddleNLP/tree/v2.0.8/examples/text_generation/unimo-text 基线中的模型改成`unimo-text-1.0-large`之后，出现如题错误。但是`unimo-text-1.0`可以正常运行。
详细报错如下：
```
Traceback (most recent call last):
  File "../run_gen.py", line 246, in <module>
    run(args)
  File "../run_gen.py", line 164, in run
    optimizer.step()
  File "<decorator-gen-198>", line 2, in step
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/adam.py", line 366, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 796, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/adamw.py", line 203, in _create_optimization_pass
    AdamW, self)._create_optimization_pass(parameters_and_grads)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/optimizer.py", line 623, in _create_optimization_pass
    self._append_optimize_op(target_block, param_and_grad)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/adamw.py", line 198, in _append_optimize_op
    self._append_decoupled_weight_decay(block, param_and_grad)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/optimizer/adamw.py", line 195, in _append_decoupled_weight_decay
    paddle.fluid.layers.assign(input=scaled_param, output=param)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 596, in assign
    type='assign', inputs={'X': [input]}, outputs={'Out': [output]})
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2950, in append_op
    kwargs.get("stop_gradient", False))
  File "/workspace/zhuhaijun/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:382)
  [operator < assign > error]
```

**Comment by ZHANG-GuiGui** [comment]
根据在CPU上运行的报错发现是由于tokenizer读取错误导致的。vocab文件在转换encoding类型的时候可能发生了一些错误，导致`pad_token_id`变成了12088，超过了`position_embedding`的张量大小。重新下载vocab文件之后可以正常运行。
