### ISSUE TITLE
ai studio平台跑程序时，报错OSError: (External)  Cublas error

### ISSUE THREAD

**Issue by rela0426** [PaddlePaddle/PaddleNLP#1215]
环境：
paddlepaddle：2.0.2
paddlenlp：2.0.1
python：3.7
aistudio地址：https://aistudio.baidu.com/studio/project/partial/verify/2501132/1a94a18324fc4a01833aea8993d5d4db

在aistudio平台上，之前程序一直正常，后来环境突然没了，按照程序依赖的环境重新搭建好以后，就出问题了。
程序执行到`!bash run_duee_1.sh trigger_train`时，报以下错误：
```python
[2021-10-21 17:45:55,045] [ WARNING] - Compatibility Warning: The params of LinearChainCrfLoss.forward has been modified. The third param is `labels`, and the fourth is not necessary. Please update the usage.
Traceback (most recent call last):
  File "sequence_labeling.py", line 309, in <module>
    do_train()
  File "sequence_labeling.py", line 219, in do_train
    loss.backward()
  File "<decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:40)
```

后来将paddlenlp更新到了2.0.2版本，就开始报另外一个错误，如下：
```python
Traceback (most recent call last):
  File "sequence_labeling.py", line 309, in <module>
    do_train()
  File "sequence_labeling.py", line 217, in do_train
    loss,logits=model(input_ids, token_type_ids,seq_lens,labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 489, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/test/BertBiGruWithCRF.py", line 54, in forward
    _, prediction = self.viterbi_decoder(emission, lengths)  # lengths 是batch size的大小
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/layers/crf.py", line 398, in forward
    for i, logit in enumerate(inputs_t[:max_seq_len]):
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows None or integers in slice item, but received Tensor. (at /paddle/paddle/fluid/pybind/imperative.cc:337)
```
能帮我看下吗，谢谢~

**Comment by ZeyuChen** [comment]
试试将paddle和paddlenlp都升级到最新的2.1.3和2.1.1版本看看是否还有此错误。@rela0426

**Comment by rela0426** [comment]
> 试试将paddle和paddlenlp都升级到最新的2.1.3和2.1.1版本看看是否还有此错误。@rela0426
嗯嗯，按照您的要求升级以后，这个错误完美解决了，但是程序跑起来以后，训练过程中，一直报下面这个错误
```
train epoch: 0 - step: 1 (total: 650) - loss: 19.485710
dev step: 1, loss:17.88780, precision: 0.00000, recall: 0.00000, f1: 0.00000 current best f1:0.00000
train epoch: 0 - step: 2 (total: 650) - loss: 27.592960
dev step: 2, loss:13.97601, precision: 0.00000, recall: 0.00000, f1: 0.00000 current best f1:0.00000
train epoch: 0 - step: 3 (total: 650) - loss: 16.176376
dev step: 3, loss:16.10207, precision: 0.00000, recall: 0.00000, f1: 0.00000 current best f1:0.00000

Traceback (most recent call last):
  File "sequence_labeling.py", line 312, in <module>
    do_train()
  File "sequence_labeling.py", line 222, in do_train
    loss.backward()
  File "<decorator-gen-122>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```
目前bach_size=2，epoch=2，训练集也不大，只有650条。
帮忙看下吧，多谢~
