### ISSUE TITLE
paddlenlp在本地电脑，显存8G，上加载预训练模型（尝试过ernie-1.0和ernie-3.0-nano-zh）后去训练数据，为什么总遇到时GPU内在不足的问题呢？

### ISSUE THREAD

**Issue by crjhonor** [PaddlePaddle/PaddleNLP#2747]
错误码如下：
```python
global step 140, epoch: 1, batch: 140, loss: 0.69705, acc: 0.54464
global step 150, epoch: 1, batch: 150, loss: 0.68403, acc: 0.54167
global step 160, epoch: 1, batch: 160, loss: 0.65066, acc: 0.53594
global step 170, epoch: 1, batch: 170, loss: 0.72706, acc: 0.53235
global step 180, epoch: 1, batch: 180, loss: 0.73757, acc: 0.52639
global step 190, epoch: 1, batch: 190, loss: 0.72412, acc: 0.52763
global step 200, epoch: 1, batch: 200, loss: 0.71383, acc: 0.52875
global step 210, epoch: 1, batch: 210, loss: 0.66676, acc: 0.53214
global step 220, epoch: 1, batch: 220, loss: 0.71038, acc: 0.52727
global step 230, epoch: 1, batch: 230, loss: 0.69849, acc: 0.52500
global step 240, epoch: 1, batch: 240, loss: 0.69703, acc: 0.52917
global step 250, epoch: 1, batch: 250, loss: 0.72493, acc: 0.52800
global step 260, epoch: 1, batch: 260, loss: 0.75677, acc: 0.52981
Traceback (most recent call last):
  File "/home/crjBeta/PycharmProjects/paddleNlp/paddlenlpHighbaseline.py", line 128, in <module>
    logits = model(inputs_ids, segment_ids)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddlenlp/transformers/ernie/modeling.py", line 735, in forward
    attention_mask=attention_mask)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddlenlp/transformers/ernie/modeling.py", line 666, in forward
    encoder_outputs = self.encoder(embedding_output, attention_mask)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 697, in forward
    output = mod(output, src_mask=src_mask)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 581, in forward
    src = self.self_attn(src, src, src, src_mask)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 410, in forward
    product = product + attn_mask
  File "/home/crjBeta/PycharmProjects/paddleNlp/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
SystemError: (Fatal) Operator elementwise_add raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 703.417969MB memory on GPU 0, 7.636902GB memory has been allocated and available memory is only 296.312500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
```

进程已结束,退出代码1

可以看到 ，在降低batch_size=1后，训练是可以进行的，但是在几百个batch后又报错显示内在不足了。难道不会自动释放内存吗？

以下是代码：（注：代码原自CSDN，感谢原作者。）

```python
import paddlenlp
import paddle
from paddlenlp.datasets import load_dataset

# Fetching DATASET.
train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=['train', 'dev', 'test'])

print(len(train_ds))
print(len(dev_ds))

from paddlenlp.transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained(pretrained_model_name_or_path="ernie-3.0-nano-zh",
                                                           num_classes=2)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path="ernie-3.0-nano-zh")

from visualdl import LogWriter

writer = LogWriter("./log")

def convert_example(example,
                    tokenizer,
                    max_seq_length=512,
                    is_test=False):
    encoded_inputs = tokenizer(text=example['text'], max_seq_length=max_seq_length)
    input_ids = encoded_inputs['input_ids']
    token_type_ids = encoded_inputs['token_type_ids']

    if not is_test:
        label = np.array([example["label"]], dtype='int64')
        return input_ids, token_type_ids, label
    else:
        qid = np.array([example["qid"]], dtype="int64")
        return input_ids, token_type_ids, qid


def create_dataloader(dataset,
                      trans_fn=None,
                      mode='train',
                      batch_size=1,
                      batchify_fn=None):
    if trans_fn:
        dataset = dataset.map(trans_fn)

    shuffle = True if mode == 'train' else False
    if mode == 'train':
        sampler = paddle.io.DistributedBatchSampler(dataset=dataset, batch_size=batch_size, shuffle=shuffle)
    else:
        sampler = paddle.io.BatchSampler(dataset=dataset, batch_size=batch_size, shuffle=shuffle)
    dataloader = paddle.io.DataLoader(dataset, batch_sampler=sampler, collate_fn=batchify_fn)
    return dataloader

import numpy as np
import paddle

@paddle.no_grad()
def evaluate(model, criterion, metric, data_loader):
    model.eval()
    metric.reset()
    for batch in data_loader:
        input_ids, token_type_ids, labels=batch
        logits = model(input_ids, token_type_ids)
        loss = criterion(logits, labels)
        losses.append(loss.numpy())
        correct = metric.compute(logits, labels)
        metric.update(correct)
        accu = metric.accumulate()
        #print("eval loss: %.5f, accu: %.5f" % (np.mean(losses), accu))
        model.train()
        metric.reset()
        return np.mean(losses), accu

import os, time
from functools import partial
import numpy as np
import paddle
import paddle.nn.functional as F
from paddlenlp.data import Stack, Tuple, Pad

batch_size = 4
max_seq_length = 166
learning_rate = 4e-5
epochs = 32
warmup_proportion = 0.1
weight_decay = 0.01

trans_func = partial(convert_example, tokenizer=tokenizer, max_seq_length=max_seq_length)

batchify_fn = lambda samples, fn=Tuple(
    Pad(axis=0, pad_val=tokenizer.pad_token_id),
    Pad(axis=0, pad_val=tokenizer.pad_token_type_id),
    Stack()
): [data for data in fn(samples)]
train_data_loader = create_dataloader(
    train_ds,
    mode='train',
    batch_size=batch_size,
    batchify_fn=batchify_fn,
    trans_fn=trans_func
)
dev_data_loader = create_dataloader(
    dev_ds,
    mode='dev',
    batch_size=batch_size,
    batchify_fn=batchify_fn,
    trans_fn=trans_func
)

from paddlenlp.transformers import LinearDecayWithWarmup

num_training_steps = len(train_data_loader) * epochs
lr_scheduler = LinearDecayWithWarmup(learning_rate, num_training_steps, warmup_proportion)
optimizer = paddle.optimizer.AdamW(
    learning_rate=lr_scheduler,
    parameters=model.parameters(),
    weight_decay=weight_decay,
    apply_decay_param_fun=lambda x: x in [p.name for n, p in model.named_parameters()
                                          if not any(nd in n for nd in ['bias', 'norm'])])

criterion = paddle.nn.loss.CrossEntropyLoss()
metric = paddle.metric.Accuracy()

# # Begining of training.-----------------------------------------------------------------------------------------------
global_step = 0
for epoch in range(1, epochs + 1):
    for step, batch in enumerate(train_data_loader, start=1):
        inputs_ids, segment_ids, labels = batch
        logits = model(inputs_ids, segment_ids)
        loss = criterion(logits, labels)
        probs = F.softmax(logits, axis=1)
        correct = metric.compute(probs, labels)
        metric.update(correct)
        acc = metric.accumulate()

        global_step += 1
        if global_step % 10 == 0:
            print("global step %d, epoch: %d, batch: %d, loss: %.5f, acc: %.5f" % (global_step, epoch, step, loss, acc))
        loss.backward()
        optimizer.step()
        optimizer.clear_grad()
    evaluate(model, criterion, metric, dev_data_loader)

model.save_pretrained('./nlp/checkpoint')
tokenizer.save_pretrained('./nlp/checkpoint')
```
- 版本、环境信息

1）PaddleNLP 2.3.4和PaddlePaddle-gpu 2.3.0
2）系统环境：操作系统deepin20.6,  pycharm pro;

**Comment by wawltor** [comment]
你可以试试先把显存清空，然后再跑跑试试 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/16698950/177500316-0bbe0de9-903c-4043-8055-f682c66c029d.png">
我自己的显存相对比较稳定，对于batch_size=1

如果想增加batch_size, 可以尝试把max_seq_len调小，可以减少到70左右

**Comment by crjhonor** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   43C    P8    15W / 180W |    383MiB /  8192MiB |     16%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3977      G   /usr/lib/xorg/Xorg                267MiB |
|    0   N/A  N/A      5225      G   kwin_x11                           48MiB |
|    0   N/A  N/A      6519      G   ...AAAAAAAAA= --shared-files       16MiB |
|    0   N/A  N/A     12448      G   ...in/deepin-deepinid-client        9MiB |
|    0   N/A  N/A     16176      G   deepin-home-appstore-client         5MiB |
|    0   N/A  N/A     17244      G   .../files/bin/sunloginclient       16MiB |
|    0   N/A  N/A     18047      G   ...d-files --enable-crashpad       12MiB |
+-----------------------------------------------------------------------------+
```
用nvidia-smi查看，运行训练前只用了不到400MB喔。

**Comment by crjhonor** [comment]
I am coming up with the idea to use multiprocessing.pool.Pool, haha. But I am not familiar with that package, I try the p.map function but get no logits return. But the memory was within controlable, although the processing speed is much more slower.

global_step = 0
logits = paddle.Tensor
from multiprocessing import Pool
def fun_model(inputs_ids, segment_ids):
    logits = model(inputs_ids, segment_ids)
    return logits
for epoch in range(1, epochs + 1):
    for step, batch in enumerate(train_data_loader, start=1):
        inputs_ids, segment_ids, labels = batch
        with Pool(1) as p:
            logits = p.apply_async(fun_model, (inputs_ids, segment_ids))
        loss = criterion(logits, labels)
        probs = F.softmax(logits, axis=1)
        correct = metric.compute(probs, labels)
        metric.update(correct)
        acc = metric.accumulate()

BUT I cannot get the logits= return right.

**Comment by LiuChiachi** [comment]
是evaluation之后显存不足的吗？正常训练的时候显存是不是已经快满了呢？
同建议减小一下`--max_seq_length`，可能之前没爆是因为还没有遇到接近`--max_seq_length`长度的数据

**Comment by jiaxingguo** [comment]
问题解决了么？遇到同样的问题，好像程序运行完后显存没有自动释放。
