### ISSUE TITLE
paddleNLP 2.3.1 paddlepaddle2.2.2 RuntimeError

### ISSUE THREAD

**Issue by www-Ye** [PaddlePaddle/PaddleNLP#2978]
paddleNLP 2.3.1 paddlepaddle2.2.2 cuda11.0
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcublas.so) that Paddle depends on is not configured correctly. (error code is libcublas.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:285)

**Comment by tianxin1860** [comment]
1. 请 check 下安装的 paddle 对应的 cuda 版本是否为 cuda11.0 ?
2. 可以参考[这里](https://blog.csdn.net/Grit_007/article/details/85000297)配置动态库路径。

**Comment by wawltor** [comment]
建议在一个新的conda环境里面，使用conda来安装paddle  https://www.paddlepaddle.org.cn/  
<img width="860" alt="image" src="https://user-images.githubusercontent.com/16698950/183326609-eb8d91ca-8a11-4ff7-b18c-3dd224b0eb1e.png">

**Comment by www-Ye** [comment]
我用pytorch的时候不会出现问题，用的也是cuda11.0的环境
然后用locate查找后找不到cuda下的libcublas，只有一个man/man7/路径下的。
请问有没有什么解决办法

---Original---
From: ***@***.***&gt;
Date: Mon, Aug 8, 2022 10:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




  
请 check 下安装的 paddle 对应的 cuda 版本是否为 cuda11.0 ?
 
可以参考这里配置动态库路径。

**Comment by wawltor** [comment]
> 我用pytorch的时候不会出现问题，用的也是cuda11.0的环境 然后用locate查找后找不到cuda下的libcublas，只有一个man/man7/路径下的。 请问有没有什么解决办法
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Aug 8, 2022 10:26 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 请 check 下安装的 paddle 对应的 cuda 版本是否为 cuda11.0 ? 可以参考这里配置动态库路径。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

建议conda安装一下环境

**Comment by www-Ye** [comment]
我尝试过用conda装2.0.2的，还是出现了一样的错误



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 8, 2022 10:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




 
建议在一个新的conda环境里面，使用conda来安装paddle  https://www.paddlepaddle.org.cn/

**Comment by wawltor** [comment]
> 我尝试过用conda装2.0.2的，还是出现了一样的错误
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Aug 8, 2022 10:32 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 建议在一个新的conda环境里面，使用conda来安装paddle https://www.paddlepaddle.org.cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是说paddle的版本是2.0.2？

**Comment by www-Ye** [comment]
是的，用conda装的2.0.2，因为2.3.1好像没有11.0的conda安装方法



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 8, 2022 11:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




  
我尝试过用conda装2.0.2的，还是出现了一样的错误
 …
 ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 10:32 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 建议在一个新的conda环境里面，使用conda来安装paddle https://www.paddlepaddle.org.cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
是说paddle的版本是2.0.2？

**Comment by wawltor** [comment]
> 是的，用conda装的2.0.2，因为2.3.1好像没有11.0的conda安装方法
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Aug 8, 2022 11:22 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 我尝试过用conda装2.0.2的，还是出现了一样的错误 … ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 10:32 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 建议在一个新的conda环境里面，使用conda来安装paddle https://www.paddlepaddle.org.cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 是说paddle的版本是2.0.2？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

有新建一个conda环境吗？ 同时2.3.1是可以conda安装的了 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/16698950/183332313-57b13055-a031-4a09-971d-f493c8f8bde7.png">

**Comment by www-Ye** [comment]
你好，我用2.3.1的conda安装会出现图片的错误，但是用对应pip安装方式可以正常安装
然后此时我的环境是cuda10.2，paddle2.3.1，用pip方式安装，还是出现了一样的问题

---Original---
From: ***@***.***&gt;
Date: Mon, Aug 8, 2022 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




  
是的，用conda装的2.0.2，因为2.3.1好像没有11.0的conda安装方法
 …
 ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 11:22 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 我尝试过用conda装2.0.2的，还是出现了一样的错误 … ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 10:32 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 建议在一个新的conda环境里面，使用conda来安装paddle https://www.paddlepaddle.org.cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 是说paddle的版本是2.0.2？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
有新建一个conda环境吗？ 同时2.3.1是可以conda安装的了

**Comment by qiudywzh** [comment]
cudnn装了吗？这是我的配置脚本

```bash
dpkg -i /cudnn-local-repo-ubuntu1804-8.4.1.50_1.0-1_amd64.deb

cd /var/cudnn-local-repo-ubuntu1804-8.4.1.50 && \
dpkg -i libcudnn8_8.4.1.50-1+cuda11.6_amd64.deb && \
dpkg -i libcudnn8-dev_8.4.1.50-1+cuda11.6_amd64.deb

cp /usr/include/cudnn.h /usr/local/cuda/include/

ln -s /usr/local/cuda/lib64/libcublas.so.11  /usr/local/cuda/lib64/libcublas.so
ln -s /usr/local/cuda/lib64/libcusolver.so.11  /usr/local/cuda/lib64/libcusolver.so
ln -s /usr/local/cuda/lib64/libcusparse.so.11  /usr/local/cuda/lib64/libcusparse.so
```

**Comment by wawltor** [comment]
> cudnn装了吗？这是我的配置脚本
> 
> ```shell
> dpkg -i /cudnn-local-repo-ubuntu1804-8.4.1.50_1.0-1_amd64.deb
> 
> cd /var/cudnn-local-repo-ubuntu1804-8.4.1.50 && \
> dpkg -i libcudnn8_8.4.1.50-1+cuda11.6_amd64.deb && \
> dpkg -i libcudnn8-dev_8.4.1.50-1+cuda11.6_amd64.deb
> 
> cp /usr/include/cudnn.h /usr/local/cuda/include/
> 
> ln -s /usr/local/cuda/lib64/libcublas.so.11  /usr/local/cuda/lib64/libcublas.so
> ln -s /usr/local/cuda/lib64/libcusolver.so.11  /usr/local/cuda/lib64/libcusolver.so
> ln -s /usr/local/cuda/lib64/libcusparse.so.11  /usr/local/cuda/lib64/libcusparse.so
> ```
如果实在安装GPU有问题的话，可以尝试使用docker来安装paddle的镜像，https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by www-Ye** [comment]
你好，我使用paddlenlp的taskflow的信息抽取uie，使用自己训练的模型，放到类里面就会失效，会输出很多奇怪的答案，直接运行还是正常输出，
使用环境是paddlepaddle2.3.1 cpu和paddlenlp2.3.4
两张图分别是在类里面调用时的输出和在类外直接调用时的正常输出



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 10, 2022 14:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




  
cudnn装了吗？这是我的配置脚本
 dpkg -i /cudnn-local-repo-ubuntu1804-8.4.1.50_1.0-1_amd64.deb cd /var/cudnn-local-repo-ubuntu1804-8.4.1.50 &amp;&amp; \ dpkg -i libcudnn8_8.4.1.50-1+cuda11.6_amd64.deb &amp;&amp; \ dpkg -i libcudnn8-dev_8.4.1.50-1+cuda11.6_amd64.deb cp /usr/include/cudnn.h /usr/local/cuda/include/ ln -s /usr/local/cuda/lib64/libcublas.so.11  /usr/local/cuda/lib64/libcublas.so ln -s /usr/local/cuda/lib64/libcusolver.so.11  /usr/local/cuda/lib64/libcusolver.so ln -s /usr/local/cuda/lib64/libcusparse.so.11  /usr/local/cuda/lib64/libcusparse.so
  
如果实在安装GPU有问题的话，可以尝试使用docker来安装paddle的镜像，https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by wawltor** [comment]
> 你好，我使用paddlenlp的taskflow的信息抽取uie，使用自己训练的模型，放到类里面就会失效，会输出很多奇怪的答案，直接运行还是正常输出， 使用环境是paddlepaddle2.3.1 cpu和paddlenlp2.3.4 两张图分别是在类里面调用时的输出和在类外直接调用时的正常输出
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Aug 10, 2022 14:37 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) cudnn装了吗？这是我的配置脚本 dpkg -i /cudnn-local-repo-ubuntu1804-8.4.1.50_1.0-1_amd64.deb cd /var/cudnn-local-repo-ubuntu1804-8.4.1.50 &amp;&amp; \ dpkg -i libcudnn8_8.4.1.50-1+cuda11.6_amd64.deb &amp;&amp; \ dpkg -i libcudnn8-dev_8.4.1.50-1+cuda11.6_amd64.deb cp /usr/include/cudnn.h /usr/local/cuda/include/ ln -s /usr/local/cuda/lib64/libcublas.so.11 /usr/local/cuda/lib64/libcublas.so ln -s /usr/local/cuda/lib64/libcusolver.so.11 /usr/local/cuda/lib64/libcusolver.so ln -s /usr/local/cuda/lib64/libcusparse.so.11 /usr/local/cuda/lib64/libcusparse.so 如果实在安装GPU有问题的话，可以尝试使用docker来安装paddle的镜像，https://hub.docker.com/r/paddlepaddle/paddle/tags — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

issue上没有您说的两张图片，可以贴一下图片和代码吗？

**Comment by www-Ye** [comment]
这里的conda安装可以安装cuda11.0的版本的paddle么



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 8, 2022 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978)




  
是的，用conda装的2.0.2，因为2.3.1好像没有11.0的conda安装方法
 …
 ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 11:22 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 我尝试过用conda装2.0.2的，还是出现了一样的错误 … ---Original--- From: @.&gt; Date: Mon, Aug 8, 2022 10:32 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] paddleNLP 2.3.1 paddlepaddle2.2.2RuntimeError: (PreconditionNotMet) The third-party dynamic library(libcublas.so) that Paddle depends on is not configured correctly. (error codeis libcublas.so: cannot open shared object file: No such file or directory)(Issue #2978) 建议在一个新的conda环境里面，使用conda来安装paddle https://www.paddlepaddle.org.cn/ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 是说paddle的版本是2.0.2？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
有新建一个conda环境吗？ 同时2.3.1是可以conda安装的了
