### ISSUE TITLE
[Question]: CodeGen部署服务的时候，使用网页请求不通

### ISSUE THREAD

**Issue by zhixue123456** [PaddlePaddle/PaddleNLP#5449]
### 请提出你的问题

网页请求得到{"detail":"Not Found"}，
日志输出为INFO:     127.0.0.1:64463 - "GET / HTTP/1.1" 404 Not Found

**Comment by gongel** [comment]
测试能通过吗？

**Comment by gongel** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E6%B5%8B%E8%AF%95%E6%9C%8D%E5%8A%A1

**Comment by Allen--Wang** [comment]
看上去是个bug。codegen_server.py:79
@app.post("/v1/engines/codegen/completions", status_code=200)
改成
@app.post("/engines/codegen/completions", status_code=200)
就能通了，但用例子返回500了。有用的信息如下
我cuda装的12，cudnn也是对应配套的，但最早有报错貌似用不了12（找不到cudnn64_7.dll），我就找了个别的目录的cudnn64_7.dll写到了path里面能起来了。想问一下cuda环境用啥？10.0？10.2？python版本呢？我现在用的3.10

RuntimeError: (PreconditionNotMet) The third-party dynamic library (cublas64_102.dll;cublas64_10.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:305)
  [operator < linear > error]
[2023-03-29 14:28:35,204] [   ERROR] h11_impl.py:369 - Exception in ASGI application

**Comment by zhixue123456** [comment]
> 测试能通过吗？
我解决了以上问题，并用fauxpilot联上了本地服务器，但是只要一开始请求服务器就得到如下错误

[2023-03-29 15:55:39,977] [    INFO] - Start generating code
INFO:     127.0.0.1:61740 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "D:\python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "D:\python38\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "D:\python38\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\python38\lib\site-packages\starlette\exceptions.py", line 93, in __call__
    raise exc
  File "D:\python38\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\python38\lib\site-packages\starlette\routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "D:\python38\lib\site-packages\starlette\routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "D:\python38\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\python38\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "D:\python38\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\python\paddlenlp\examples\code_generation\codegen\codegen_server.py", line 92, in gen
    output, _ = model.generate(
  File "D:\python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 850, in generate
    return self.greedy_search(
  File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 947, in greedy_search
    outputs = self(**model_inputs)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 648, in forward
    transformer_outputs = self.transformer(
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 487, in forward
    outputs = block(
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 257, in forward
    attn_outputs = self.attn(
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 186, in forward
    k_rot = apply_rotary_pos_emb(k_rot, sincos, offset=offset)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 78, in apply_rotary_pos_emb
    return (x * cos) + (rotate_every_two(x) * sin)
  File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 64, in rotate_every_two
    x1 = x[:, :, :, ::2]
  File "D:\python38\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 740, in __getitem__
    return self._getitem_index_not_tensor(item)
RuntimeError: (NotFound) There are no kernels which are registered in the strided_slice operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:341)

**Comment by zhixue123456** [comment]
cuda用的10.2,python3.8

**Comment by gongel** [comment]
版本问题：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/code_generation/codegen/requirements.txt#L6

**Comment by zhixue123456** [comment]
> 版本问题：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/code_generation/codegen/requirements.txt#L6

我降低python版本解决了该问题，后续生成成功调用，但是生成内容只有！
[2023-03-29 16:05:52,810] [    INFO] - Start generating code
[2023-03-29 16:05:52,990] [    INFO] - Finish generating code
[2023-03-29 16:05:52,991] [    INFO] - Time cost: 0.18152546882629395
[2023-03-29 16:05:52,994] [    INFO] - Generated code: !
INFO:     127.0.0.1:63833 - "POST /v1/engines/codegen/completions HTTP/1.1" 200 OK
[2023-03-29 16:05:53,102] [    INFO] - Request: {'prompt': 'import openai\r\ndef openaitest():\r\n    openai.api_key = \'dummy\'\r\n    openai.api_base = \'http://127.0.0.1:8978\'\r\n    result = openai.Completion.create(\r\n        engine=\'codegen\', prompt=\'def hello\', max_tokens=16, temperature=0.1)\r\n    print(result)\r\nlog_path = "2023-03-27_18-51-24-989546(4.1.2.10004).log"\r\nwith open(log_path,encoding=\'utf-8\') as f:\r\n    f.read()\r\n\r\n#调用', 'stream': False}
[2023-03-29 16:05:53,103] [    INFO] - Start generating code
[2023-03-29 16:05:53,280] [    INFO] - Finish generating code
[2023-03-29 16:05:53,281] [    INFO] - Time cost: 0.17859983444213867
[2023-03-29 16:05:53,283] [    INFO] - Generated code: !
INFO:     127.0.0.1:63835 - "POST /v1/engines/codegen/completions HTTP/1.1" 200 OK
[2023-03-29 16:05:55,571] [    INFO] - Request: {'prompt': 'import openai\r\ndef openaitest():\r\n    openai.api_key = \'dummy\'\r\n    openai.api_base = \'http://127.0.0.1:8978\'\r\n    result = openai.Completion.create(\r\n        engine=\'codegen\', prompt=\'def hello\', max_tokens=16, temperature=0.1)\r\n    print(result)\r\nlog_path = "2023-03-27_18-51-24-989546(4.1.2.10004).log"\r\nwith open(log_path,encoding=\'utf-8\') as f:\r\n    f.read()\r\n\r\n#调用o', 'stream': False}

**Comment by Town-zh** [comment]
想问下你这个python版本是多少？然后可以预测java语言吗？

**Comment by Zhaiaiguo518** [comment]
> > 测试能通过吗？
> > 我解决了以上问题，并用fauxpilot联上了本地服务器，但是只要一开始请求服务器就得到如下错误
> 
> [2023-03-29 15:55:39,977] [ INFO] - Start generating code INFO: 127.0.0.1:61740 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "D:\python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi result = await app(self.scope, self.receive, self.send) File "D:\python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in **call** return await self.app(scope, receive, send) File "D:\python38\lib\site-packages\fastapi\applications.py", line 269, in **call** await super().**call**(scope, receive, send) File "D:\python38\lib\site-packages\starlette\applications.py", line 124, in **call** await self.middleware_stack(scope, receive, send) File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 184, in **call** raise exc File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 162, in **call** await self.app(scope, receive, _send) File "D:\python38\lib\site-packages\starlette\exceptions.py", line 93, in **call** raise exc File "D:\python38\lib\site-packages\starlette\exceptions.py", line 82, in **call** await self.app(scope, receive, sender) File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in **call** raise e File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in **call** await self.app(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 670, in **call** await route.handle(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 266, in handle await self.app(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 65, in app response = await func(request) File "D:\python38\lib\site-packages\fastapi\routing.py", line 227, in app raw_response = await run_endpoint_function( File "D:\python38\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function return await dependant.call(**values) File "D:\python\paddlenlp\examples\code_generation\codegen\codegen_server.py", line 92, in gen output, _ = model.generate( File "D:\python38\lib\site-packages\decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 354, in _decorate_function return func(*args, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 850, in generate return self.greedy_search( File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 947, in greedy_search outputs = self(**model_inputs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 648, in forward transformer_outputs = self.transformer( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 487, in forward outputs = block( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 257, in forward attn_outputs = self.attn( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 186, in forward k_rot = apply_rotary_pos_emb(k_rot, sincos, offset=offset) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 78, in apply_rotary_pos_emb return (x * cos) + (rotate_every_two(x) * sin) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 64, in rotate_every_two x1 = x[:, :, :, ::2] File "D:\python38\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 740, in **getitem** return self._getitem_index_not_tensor(item) RuntimeError: (NotFound) There are no kernels which are registered in the strided_slice operator. [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:341)

hello  我也遇到这个问题  请问您是怎么解决的？

**Comment by gongel** [comment]
> > > 测试能通过吗？
> > > 我解决了以上问题，并用fauxpilot联上了本地服务器，但是只要一开始请求服务器就得到如下错误
> > 
> > 
> > [2023-03-29 15:55:39,977] [ INFO] - Start generating code INFO: 127.0.0.1:61740 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "D:\python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi result = await app(self.scope, self.receive, self.send) File "D:\python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in **call** return await self.app(scope, receive, send) File "D:\python38\lib\site-packages\fastapi\applications.py", line 269, in **call** await super().**call**(scope, receive, send) File "D:\python38\lib\site-packages\starlette\applications.py", line 124, in **call** await self.middleware_stack(scope, receive, send) File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 184, in **call** raise exc File "D:\python38\lib\site-packages\starlette\middleware\errors.py", line 162, in **call** await self.app(scope, receive, _send) File "D:\python38\lib\site-packages\starlette\exceptions.py", line 93, in **call** raise exc File "D:\python38\lib\site-packages\starlette\exceptions.py", line 82, in **call** await self.app(scope, receive, sender) File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in **call** raise e File "D:\python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in **call** await self.app(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 670, in **call** await route.handle(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 266, in handle await self.app(scope, receive, send) File "D:\python38\lib\site-packages\starlette\routing.py", line 65, in app response = await func(request) File "D:\python38\lib\site-packages\fastapi\routing.py", line 227, in app raw_response = await run_endpoint_function( File "D:\python38\lib\site-packages\fastapi\routing.py", line 160, in run_endpoint_function return await dependant.call(**values) File "D:\python\paddlenlp\examples\code_generation\codegen\codegen_server.py", line 92, in gen output, _ = model.generate( File "D:\python38\lib\site-packages\decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 354, in _decorate_function return func(*args, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 850, in generate return self.greedy_search( File "D:\python38\lib\site-packages\paddlenlp\transformers\generation_utils.py", line 947, in greedy_search outputs = self(**model_inputs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 648, in forward transformer_outputs = self.transformer( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 487, in forward outputs = block( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 257, in forward attn_outputs = self.attn( File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 186, in forward k_rot = apply_rotary_pos_emb(k_rot, sincos, offset=offset) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 78, in apply_rotary_pos_emb return (x * cos) + (rotate_every_two(x) * sin) File "D:\python38\lib\site-packages\paddlenlp\transformers\codegen\modeling.py", line 64, in rotate_every_two x1 = x[:, :, :, ::2] File "D:\python38\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 740, in **getitem** return self._getitem_index_not_tensor(item) RuntimeError: (NotFound) There are no kernels which are registered in the strided_slice operator. [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at ..\paddle\fluid\imperative\prepared_operator.cc:341)
> 
> hello 我也遇到这个问题 请问您是怎么解决的？

PaddlePaddle升级到最新版
