### ISSUE TITLE
文本分类 multi_class 使用GPU inference报错 

### ISSUE THREAD

**Issue by White2White** [PaddlePaddle/PaddleNLP#5471]
### 请提出你的问题

dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory) [2023-03-30 13:23:56]   Suggestions: [2023-03-30 13:23:56]   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed. [2023-03-30 13:23:56]   2. Configure third-party dynamic library environment variables as follows: [2023-03-30 13:23:56]   - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...` [2023-03-30 13:23:56]   - Windows: set PATH by `set PATH=XXX;

**Comment by w5688414** [comment]
cuda安装不正确。请根据官网的教程检查一下。

安装完成后您可以使用 python3 进入 python 解释器，输入import paddle ，再输入 paddle.utils.run_check()

如果出现PaddlePaddle is installed successfully!，说明您已成功安装。

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by White2White** [comment]
但是我的其他模型在同一个容器中可以正常运行，说明我的cuda安装没有问题。

**Comment by White2White** [comment]
我尝试使用了nvidia官方的镜像，依然存在相同的问题
