### ISSUE TITLE
[Question]: OSError: (External) CUBLAS error(7)

### ISSUE THREAD

**Issue by LiemLin** [PaddlePaddle/PaddleNLP#5589]
### 请提出你的问题

显卡信息：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

飞桨版本信息
paddle-pipelines          0.5.2        
paddle2onnx               1.0.6            
paddlefsl                 1.1.0        
paddlenlp                 2.5.2            
paddleocr                 2.6.1.3          
paddlepaddle-gpu          2.4.2.post116

飞桨检查正常
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0410 16:38:46.079973 11374 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 11.6
W0410 16:38:46.094743 11374 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.        

但是执行python examples/unsupervised-question-answering/unsupervised_question_answering_example.py --device gpu --source_file data/source_file.txt --doc_dir data/my_data --index_name faiss_index --retriever_batch_size 16
报下面的错误
OSError: (External) CUBLAS error(7). 
  [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < fc > error]

请问是飞桨的BUG吗

**Comment by LiemLin** [comment]
@linjieccc 我这个和之前其他人提的不太一样，我执行paddle.utils.run_check()是成功的，大佬帮忙看看吧

**Comment by LiemLin** [comment]
用cpu执行样例也报错，--device cpu 参数没起作用
unset CUDA_VISIBLE_DEVICES
python examples/unsupervised-question-answering/unsupervised_question_answering_example.py --device cpu --source_file data/source_file.txt --doc_dir data/my_data

/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023-04-11 13:44:04,625] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/home/ai/.paddlenlp/pipelines/unsupervised_question_answering/uie-base-answer-extractor'.
Traceback (most recent call last):
  File "/home/ai/qa/PaddleNLP/pipelines/examples/unsupervised-question-answering/unsupervised_question_answering_example.py", line 153, in <module>
    qa_generation_pipeline()
  File "/home/ai/qa/PaddleNLP/pipelines/examples/unsupervised-question-answering/unsupervised_question_answering_example.py", line 110, in qa_generation_pipeline
    question_generator = QuestionGenerator(
  File "/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/paddle_pipelines-0.5.2-py3.9.egg/pipelines/nodes/question_generator/question_generator.py", line 114, in __init__
    self.question_generation = Taskflow(
  File "/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 837, in __init__
    self.task_instance = task_class(
  File "/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/paddlenlp/taskflow/question_generation.py", line 47, in __init__
    paddle.set_device(kwargs.get("device", "gpu"))
  File "/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/paddle/device/__init__.py", line 316, in set_device
    place = _convert_to_place(device)
  File "/home/ai/miniconda3/envs/qa/lib/python3.9/site-packages/paddle/device/__init__.py", line 202, in _convert_to_place
    raise ValueError("The device should not be 'gpu', "
ValueError: The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA

**Comment by LiemLin** [comment]
此问题已经解决，有同样问题的同学可以下载新版的cudnn尝试https://developer.download.nvidia.cn/compute/cudnn/secure/8.8.1/local_installers/11.8/cudnn-linux-x86_64-8.8.1.3_cuda11-archive.tar.xz
