### ISSUE TITLE
Bert+CRF GPU内核启动失败

### ISSUE THREAD

**Issue by ZeqiangWangAI** [PaddlePaddle/PaddleNLP#722]
版本信息
paddlehub              2.0.4          
paddlenlp              2.0.1          
paddlepaddle-gpu       2.1.0.post101  
错误问题：
在Bert模型上加了一个CRF层
class BertCrfForTokenClassification(nn.Layer):
    def __init__(self, bert, crf_lr=100):
        super().__init__()
        self.num_classes = bert.num_classes
        self.bert = bert  # allow bert to be config
        self.crf = LinearChainCrf(
            self.num_classes, crf_lr=crf_lr, with_start_stop_tag=False)
        self.crf_loss = LinearChainCrfLoss(self.crf)
        self.viterbi_decoder = ViterbiDecoder(
            self.crf.transitions, with_start_stop_tag=False)

    def forward(self,
                input_ids,
                token_type_ids=None,
                position_ids=None,
                attention_mask=None,
                lengths=None,
                labels=None):
        logits = self.bert(
                input_ids,
                token_type_ids=token_type_ids,
                position_ids=position_ids,
                attention_mask=attention_mask)

        if labels is not None:
            loss = self.crf_loss(logits, lengths, labels)
            return loss
        else:
            _, prediction = self.viterbi_decoder(logits, lengths)
            return prediction
报错信息-能够正常训练两个steps：
global step 1, epoch: 0, batch: 0, loss: 205.606583, speed: 2.10 step/s
global step 2, epoch: 0, batch: 1, loss: 141.633408, speed: 1.10 step/s
Traceback (most recent call last):
  File "./train_crf.py", line 219, in <module>
    do_train(args)
  File "./train_crf.py", line 203, in do_train
    avg_loss.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 236, in backward
    framework._dygraph_tracer())
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:40)

**Comment by wawltor** [comment]
您好 请升级一下PaddleNLP最新的版本，在最新的版本中我们已经修复了问题

**Comment by ZeqiangWangAI** [comment]
> 您好 请升级一下PaddleNLP最新的版本，在最新的版本中我们已经修复了问题

已经将paddlenlp更新到2.0.5问题还是会出现

**Comment by KinvenW** [comment]
你好，请问你的问题解决了吗，我也遇到了同样的问题

**Comment by ZeqiangWangAI** [comment]
> 你好，请问你的问题解决了吗，我也遇到了同样的问题

解决了 您可以看一个关于BERT+LSTM+CRF的issue，通过设置ignore_label解决的这一问题

**Comment by chenxiaozeng** [comment]
可参考这里解决~https://github.com/PaddlePaddle/PaddleNLP/issues/743
